# fly.toml app configuration file generated for morning-silence-3379 on 2023-07-19T19:13:09+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "morning-silence-3379"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
